apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
      - image: okteto.dev/one:latest
        name: one
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "429b2226-3013-4513-8e59-f7576918c0f5"
        - name: Vless_Path
          value: "/ujwhsn5ahw2"
        - name: Vmess_UUID
          value: "429b2226-3013-4513-8e59-f7576918c0f5"
        - name: Vmess_Path
          value: "/wsdcf18ghjms"
        - name: Share_Path
          value: "/share233"
