apiVersion: apps/v1
kind: Deployment
metadata:
  name: four
spec:
  replicas: 1
  selector:
    matchLabels:
      app: four
  template:
    metadata:
      labels:
        app: four
    spec:
      containers:
      - image: okteto.dev/four:latest
        name: four
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "9b40171a-8614-466e-8708-bd0b14743286"
        - name: Vless_Path
          value: "/0y19d3ece74a"
        - name: Vmess_UUID
          value: "9b40171a-8614-466e-8708-bd0b14743286"
        - name: Vmess_Path
          value: "/6b74a1c936dd"
        - name: Share_Path
          value: "/share233"
