apiVersion: apps/v1
kind: Deployment
metadata:
  name: three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three
  template:
    metadata:
      labels:
        app: three
    spec:
      containers:
      - image: okteto.dev/three:latest
        name: three
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "a713cf25-54d4-4b45-b09f-1876bbae1fce"
        - name: Vless_Path
          value: "/571rf725b8"
        - name: Vmess_UUID
          value: "a713cf25-54d4-4b45-b09f-1876bbae1fce"
        - name: Vmess_Path
          value: "/bvd5b91o29"
        - name: Share_Path
          value: "/share233"
