apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
      - image: okteto.dev/one:latest
        name: one
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: ""
        - name: Vless_UUID
          value: "273d7707-9bb1-44ff-b24c-b59876344cac"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "273d7707-9bb1-44ff-b24c-b59876344cac"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
