apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
      - image: okteto.dev/two:latest
        name: two
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "8cfdb002-0bc8-4fb5-99f5-848ad88c7623"
        - name: Vless_Path
          value: "/hw1soe9lf6"
        - name: Vmess_UUID
          value: "8cfdb002-0bc8-4fb5-99f5-848ad88c7623"
        - name: Vmess_Path
          value: "/wujah2y1as"
        - name: Share_Path
          value: "/share233"
