apiVersion: apps/v1
kind: Deployment
metadata:
  name: five
spec:
  replicas: 1
  selector:
    matchLabels:
      app: five
  template:
    metadata:
      labels:
        app: five
    spec:
      containers:
      - image: okteto.dev/five:latest
        name: five
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "3bdb4bd7-b20d-46e8-8e73-098271b35bf6"
        - name: Vless_Path
          value: "/00859aa97a05"
        - name: Vmess_UUID
          value: "3bdb4bd7-b20d-46e8-8e73-098271b35bf6"
        - name: Vmess_Path
          value: "/f9499328b58f"
        - name: Share_Path
          value: "/share233"
